// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "apzxto1N1ahX06AD5sSWx4vGCIU5B56CIcxpZTgiQKGSnwmTGOmyOkZ3R6dIJRM2DLnpGE";
}
}
}

